.TH "face" 3 "Thu Feb 18 2016" "RubiksCube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
face \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <define\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcolor\fP"
.br
.ti -1c
.RI "int \fBfinalPos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file define\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int face::color"

.PP
Definition at line 5 of file define\&.h\&.
.SS "int face::finalPos"

.PP
Definition at line 6 of file define\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RubiksCube from the source code\&.
