.TH "Input" 3 "Thu Feb 18 2016" "RubiksCube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input \- 
.PP
Status de touche du clavier (appuyé ou non)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <display\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBkey\fP [SDLK_LAST]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Status de touche du clavier (appuyé ou non) 
.PP
Definition at line 44 of file display\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char Input::key[SDLK_LAST]"
Tableau de touche avec des données avec une valeur 0 ou 1 (0 pour non appuyé et 1 pour appuyé) 
.PP
Definition at line 45 of file display\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RubiksCube from the source code\&.
