.TH "list" 3 "Thu Feb 18 2016" "RubiksCube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpTree\fP \fBtree\fP"
.br
.ti -1c
.RI "struct \fBlist\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file list\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBlist\fP* list::next"

.PP
Definition at line 8 of file list\&.h\&.
.SS "\fBpTree\fP list::tree"

.PP
Definition at line 7 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RubiksCube from the source code\&.
