.TH "src/main.c" 3 "Thu Feb 18 2016" "RubiksCube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cube\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'test/test\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmenu\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.RI "\fIGestion du menu et lance le programme\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 51 of file main\&.c\&.
.SS "void menu (\fBminiCube\fPcube[6][N][N])"

.PP
Gestion du menu et lance le programme\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcube\fP Rubik's cube initialisé 
.RE
.PP

.PP
Definition at line 21 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RubiksCube from the source code\&.
