.TH "src/resolution_mecanique.h" 3 "Thu Feb 18 2016" "RubiksCube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/resolution_mecanique.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'define\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrecherche_case\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP], int x)"
.br
.ti -1c
.RI "void \fBresolution_mecanique\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int recherche_case (\fBminiCube\fPcube[6][N][N], intx)"

.PP
Definition at line 9 of file resolution_mecanique\&.c\&.
.SS "void resolution_mecanique (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 1890 of file resolution_mecanique\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RubiksCube from the source code\&.
