.TH "src/resolution_mecanique.c" 3 "Thu Feb 18 2016" "RubiksCube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/resolution_mecanique.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'test/test\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'file\&.h'\fP
.br
\fC#include 'rotations\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrecherche_case\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP], int x)"
.br
.ti -1c
.RI "void \fBwhite_center_placement\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fBwhite_cross\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fBwhite_face\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fBsecond_line_1\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fBsecond_line_2\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fBsecond_line_3\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fBsecond_line_4\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fBsecond_line\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fByellow_cross\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.ti -1c
.RI "void \fByellow_cross_right_orientation\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP], int p)"
.br
.ti -1c
.RI "void \fByellow_corners_right_placement\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP], int p)"
.br
.ti -1c
.RI "void \fByellow_corners_right_orientation\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP], int p)"
.br
.ti -1c
.RI "void \fBresolution_mecanique\fP (\fBminiCube\fP cube[6][\fBN\fP][\fBN\fP])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int recherche_case (\fBminiCube\fPcube[6][N][N], intx)"

.PP
Definition at line 9 of file resolution_mecanique\&.c\&.
.SS "void resolution_mecanique (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 1890 of file resolution_mecanique\&.c\&.
.SS "void second_line (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 1565 of file resolution_mecanique\&.c\&.
.SS "void second_line_1 (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 1241 of file resolution_mecanique\&.c\&.
.SS "void second_line_2 (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 1322 of file resolution_mecanique\&.c\&.
.SS "void second_line_3 (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 1401 of file resolution_mecanique\&.c\&.
.SS "void second_line_4 (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 1484 of file resolution_mecanique\&.c\&.
.SS "void white_center_placement (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 26 of file resolution_mecanique\&.c\&.
.SS "void white_cross (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 59 of file resolution_mecanique\&.c\&.
.SS "void white_face (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 496 of file resolution_mecanique\&.c\&.
.SS "void yellow_corners_right_orientation (\fBminiCube\fPcube[6][N][N], intp)"

.PP
Definition at line 1784 of file resolution_mecanique\&.c\&.
.SS "void yellow_corners_right_placement (\fBminiCube\fPcube[6][N][N], intp)"

.PP
Definition at line 1700 of file resolution_mecanique\&.c\&.
.SS "void yellow_cross (\fBminiCube\fPcube[6][N][N])"

.PP
Definition at line 1576 of file resolution_mecanique\&.c\&.
.SS "void yellow_cross_right_orientation (\fBminiCube\fPcube[6][N][N], intp)"

.PP
Definition at line 1628 of file resolution_mecanique\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RubiksCube from the source code\&.
