.TH "src/resolveBacktrack.h" 3 "Thu Feb 18 2016" "RubiksCube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/resolveBacktrack.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'define\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBresolveBacktrack\fP (\fBminiCube\fP c[6][\fBN\fP][\fBN\fP])"
.br
.RI "\fILance la résolution avec l'algorithme de Backtrack afin de trouver une solution optimal\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void resolveBacktrack (\fBminiCube\fPc[6][N][N])"

.PP
Lance la résolution avec l'algorithme de Backtrack afin de trouver une solution optimal\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Rubik's cube initialisé 
.RE
.PP

.PP
Definition at line 18 of file resolveBacktrack\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RubiksCube from the source code\&.
