.TH "tree" 3 "Thu Feb 18 2016" "RubiksCube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tree\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBrotation\fP"
.br
.ti -1c
.RI "\fBminiCube\fP \fBcubeState\fP [6][\fBN\fP][\fBN\fP]"
.br
.ti -1c
.RI "char * \fBstep\fP"
.br
.ti -1c
.RI "struct \fBtree\fP * \fBbrother\fP"
.br
.ti -1c
.RI "struct \fBtree\fP * \fBchildren\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file tree\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBtree\fP* tree::brother"

.PP
Definition at line 10 of file tree\&.h\&.
.SS "struct \fBtree\fP* tree::children"

.PP
Definition at line 11 of file tree\&.h\&.
.SS "\fBminiCube\fP tree::cubeState[6][\fBN\fP][\fBN\fP]"

.PP
Definition at line 8 of file tree\&.h\&.
.SS "char* tree::rotation"

.PP
Definition at line 7 of file tree\&.h\&.
.SS "char* tree::step"

.PP
Definition at line 9 of file tree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RubiksCube from the source code\&.
